AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation template to deploy the Kittens Carousel web application

#Parameters:

Resources:
  
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Enable HTTP and SSH for webserver
      GroupName: WebServerSecGrp
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b5eea76982371e91
      KeyName: CodeRell
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref WebServerSecurityGroup
      Tags: 
        - Key: Key
          Value: WebServer-CodeRell
      UserData:
        Fn::Base64:
        |
          #!/bin/bash -x
          yum update -y
          yum install httpd -y
          cd /var/wwww/html
          FOLDER="https://raw.githubusercontent.com/CodeRell/my-repositories/main/Project-101-kittens-carousel-static-website-ec2/static-web/"
          wget ${FOLDER}index.html
          wget ${FOLDER}cat0.jpg
          wget ${FOLDER}cat1.jpg
          wget ${FOLDER}cat2.jpg
          wget ${FOLDER}cat3.png
          systemctl start httpd
          systemctl enable httpd




#Outputs: