AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation template for roman numerals web app
Parameters:

   KeyPair:
    Description: Key Pair for EC2 Instance
    Type: AWS::EC2::KeyPair::KeyName

Resources:

 WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Enable HTTP and SSH for webserver
      GroupName: WebServerSecGrp
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b5eea76982371e91
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref WebServerSecurityGroup
      Tags: 
        - Key: Name
          Value: WebServer-CodeRell
      UserData:
# Outputs: